// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeantgvssdovyvkfnout.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYW50Z3Zzc2Rvdnl2a2Zub3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTk4MjQsImV4cCI6MjA2NDg3NTgyNH0.X6AjEq-0COdD5nt3yNTqTWs6weDjJf1Cus7fRHWYh2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});